#!/bin/bash
#SBATCH --job-name=k_4_priv_20_genRR_n_10000
#SBATCH --nodes=1
#SBATCH --time=99:59:59
#SBATCH --mem=4gb
#SBATCH --partition=all
#SBATCH --nodelist=cpu-compute
#SBATCH --output=/mnt/nas/users/$(whoami)/LDPUts/simul/power/gaboardi/k_4/priv_20/k_4_priv_20_genRR_n_10000.out
#SBATCH --error=/mnt/nas/users/$(whoami)/LDPUts/simul/power/gaboardi/k_4/priv_20/k_4_priv_20_genRR_n_10000.err
CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=user212_env_cpu
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH
python /mnt/nas/users/$(whoami)/LDPUts/simul/power/gaboardi/k_4/priv_20/k_4_priv_20_genRR_n_10000.py
