#!/bin/bash 
#SBATCH --job-name=k_4_priv_005_bitflip_projchi_n100000
#SBATCH --partition=all
#SBATCH --account=user213
#SBATCH --mem=40gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=99:59:59
#SBATCH --output=/mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_4/priv_005/bitflip_projchi/k_4_priv_005_bitflip_projchi_n100000.out
#SBATCH --nodelist=gpu-compute

CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=user212_env_cpu
ENV_PATH=/mnt/nas/users/user213/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH
python /mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_4/priv_005/bitflip_projchi/k_4_priv_005_bitflip_projchi_n100000.py
