#!/bin/bash 
#
#SBATCH --job-name=k_4_priv_20_bitflip_n_10000
#SBATCH --partition=all
#SBATCH --account=user213
#SBATCH --mem=4gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=99:59:59
#SBATCH --output=/mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_4/priv_20/k_4_priv_20_bitflip_n_10000.out
#SBATCH --nodelist=cpu-compute

CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=user212_env_cpu
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH

python -u /mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_4/priv_20/k_4_priv_20_bitflip_n_10000.py > /mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_4/priv_20/k_4_priv_20_bitflip_n_10000.out
