#!/bin/bash 
#
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gpus-per-task=k40:1
#SBATCH --cpus-per-task=8
#SBATCH --time=23:59:59






#SBATCH --mem=22888mb
#SBATCH --job-name=/home1/jongminm/LDPUts/experiment/check_coding_error/power_ptbunif_k1000_ell2_bitflip_nonprivate.job
#SBATCH --output=/home1/jongminm/LDPUts/experiment/check_coding_error/power_ptbunif_k1000_ell2_bitflip_nonprivate.out
module purge
load conda
eval "$(conda shell.bash hook)"
conda activate LDPUtsEnvK40

python -u  /home1/jongminm/LDPUts/experiment/check_coding_error/power_ptbunif_k1000_ell2_bitflip_nonprivate.py > /home1/jongminm/LDPUts/experiment/check_coding_error/power_ptbunif_k1000_ell2_bitflip_nonprivate.out
