#!/bin/bash 
#
#SBATCH --job-name=k_2000_priv_20_bitflip_ell2_n_250000_high_sig
#SBATCH --partition=all
#SBATCH --account=user213
#SBATCH --mem=4gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=99:59:59
#SBATCH --output=/mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_2000/priv_20/lapu_ell2/k_2000_priv_20_lapu_ell2_n_200000_high_sig.out
#SBATCH --nodelist=gpu-compute

CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=mjmGPUenv
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH

python -u /mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_2000/priv_20/lapu_ell2/k_2000_priv_20_lapu_ell2_n_200000_high_sig.py > /mnt/nas/users/user213/LDPUts/simul/power/gaboardi/k_2000/priv_20/lapu_ell2/k_2000_priv_20_lapu_ell2_n_200000_high_sig.out
